cookie:
  expiry_days: 30
  key: pr_agent_auth_secret_key
  name: pr_agent_auth
credentials:
  usernames:
    admin:
      email: admin@pragent.com
      name: Administrator
      password: $2b$12$G5j7jSSt8xOE9yICktUqGuIT3GrJGxHTvSqvWDJVtlcEOxtjH.CLy
    pankaj:
      email: papaw.lager_1u@icloud.com
      name: Pankaj Shaky
      password: $2b$12$ibmehfJsKmG.yKcXiQutFODdt3lVmanRPLyWuCvtzPRnfJBfb3TGO
pre-authorized:
  emails:
  - admin@pragent.com
