"""
GitHub Commenter Module.

Handles posting comments to GitHub Pull Requests via the GitHub API.
"""

import os
import logging
from typing import Optional
from github import Github

logger = logging.getLogger(__name__)


class GitHubCommenter:
    """Posts comments to GitHub Pull Requests."""
    
    def __init__(self, token: Optional[str] = None):
        """
        Initialize the GitHub commenter.
        
        Args:
            token: GitHub personal access token or GitHub Actions token.
                   If not provided, uses GITHUB_TOKEN environment variable.
        """
        self.token = token or os.getenv("GITHUB_TOKEN")
        if not self.token:
            raise ValueError("GitHub token is required. Set GITHUB_TOKEN env variable or pass token parameter.")
        
        self.github = Github(self.token)
    
    def post_comment(self, repo: str, pr_number: int, body: str) -> bool:
        """
        Post a comment to a pull request.
        
        Args:
            repo: Repository in format 'owner/repo'
            pr_number: Pull request number
            body: Comment body (markdown supported)
            
        Returns:
            True if comment was posted successfully, False otherwise
        """
        try:
            repository = self.github.get_repo(repo)
            pr = repository.get_pull(pr_number)
            
            # Check if we already have a PR-Agent comment to update
            existing_comment = self._find_existing_comment(pr)
            
            if existing_comment:
                # Update existing comment
                existing_comment.edit(body)
                logger.info(f"Updated existing comment on PR #{pr_number}")
            else:
                # Create new comment
                pr.create_issue_comment(body)
                logger.info(f"Created new comment on PR #{pr_number}")
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to post comment: {e}")
            return False
    
    def _find_existing_comment(self, pr):
        """
        Find an existing PR-Agent comment to update instead of creating a new one.
        
        Args:
            pr: GitHub PR object
            
        Returns:
            Existing comment object or None
        """
        try:
            for comment in pr.get_issue_comments():
                # Look for our signature in the comment
                if "PR-Agent Analysis" in comment.body or "Generated by [PR-Agent]" in comment.body:
                    return comment
        except Exception as e:
            logger.warning(f"Could not search for existing comments: {e}")
        
        return None
    
    def post_review(self, repo: str, pr_number: int, body: str, 
                    event: str = "COMMENT", comments: Optional[list] = None) -> bool:
        """
        Post a pull request review.
        
        Args:
            repo: Repository in format 'owner/repo'
            pr_number: Pull request number
            body: Review body
            event: Review event type (APPROVE, REQUEST_CHANGES, COMMENT)
            comments: List of inline comments (optional)
            
        Returns:
            True if review was posted successfully, False otherwise
        """
        try:
            repository = self.github.get_repo(repo)
            pr = repository.get_pull(pr_number)
            
            # Get the latest commit
            commit = pr.get_commits().reversed[0]
            
            # Create the review
            pr.create_review(
                commit=commit,
                body=body,
                event=event,
                comments=comments or []
            )
            
            logger.info(f"Posted review ({event}) on PR #{pr_number}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to post review: {e}")
            return False
    
    def add_labels(self, repo: str, pr_number: int, labels: list) -> bool:
        """
        Add labels to a pull request.
        
        Args:
            repo: Repository in format 'owner/repo'
            pr_number: Pull request number
            labels: List of label names to add
            
        Returns:
            True if labels were added successfully, False otherwise
        """
        try:
            repository = self.github.get_repo(repo)
            issue = repository.get_issue(pr_number)
            
            for label in labels:
                try:
                    issue.add_to_labels(label)
                except Exception:
                    # Label might not exist, try to create it
                    try:
                        repository.create_label(name=label, color="0366d6")
                        issue.add_to_labels(label)
                    except Exception as e:
                        logger.warning(f"Could not add label '{label}': {e}")
            
            logger.info(f"Added labels {labels} to PR #{pr_number}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to add labels: {e}")
            return False
    
    def react_to_comment(self, repo: str, comment_id: int, reaction: str = "+1") -> bool:
        """
        Add a reaction to a comment.
        
        Args:
            repo: Repository in format 'owner/repo'
            comment_id: Comment ID
            reaction: Reaction type (+1, -1, laugh, confused, heart, hooray, rocket, eyes)
            
        Returns:
            True if reaction was added successfully, False otherwise
        """
        try:
            repository = self.github.get_repo(repo)
            comment = repository.get_issue_comment(comment_id)
            comment.create_reaction(reaction)
            
            logger.info(f"Added reaction {reaction} to comment {comment_id}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to add reaction: {e}")
            return False


# Convenience function for quick usage
def post_pr_comment(repo: str, pr_number: int, body: str, 
                    token: Optional[str] = None) -> bool:
    """
    Quick function to post a comment to a PR.
    
    Args:
        repo: Repository in format 'owner/repo'
        pr_number: Pull request number  
        body: Comment body
        token: GitHub token (optional, uses env var if not provided)
        
    Returns:
        True if successful, False otherwise
    """
    try:
        commenter = GitHubCommenter(token)
        return commenter.post_comment(repo, pr_number, body)
    except Exception as e:
        logger.error(f"Failed to post comment: {e}")
        return False
